name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck (scripts/**/*.sh)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck (strict)
        run: bash scripts/tools/lint_shell.sh --strict

  terraform:
    name: Terraform fmt/validate (infra/terraform)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: terraform fmt (auto-fix on push)
        if: github.event_name == 'push'
        run: |
          bash scripts/tools/fmt_terraform.sh --write
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: terraform fmt (auto-fix)"
            git push
          fi

      - name: terraform fmt -check -recursive (with diff)
        run: bash scripts/tools/fmt_terraform.sh --check

      - name: terraform init (no backend)
        run: bash scripts/tools/fmt_terraform.sh --validate
